apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack
  namespace: argocd
spec:
  source:
    path: manifests/base/localstack
    repoURL: git@github.com:imcbeth/homelab.git
    targetRevision: HEAD
  destination:
    namespace: localstack
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      enabled: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true