    apiVersion: v1
    kind: Secret
    metadata:
      name: metallb-helm-repo
      namespace: argocd # Or your Argo CD namespace
      labels:
        argocd.argoproj.io/secret-type: repository
    stringData:
      url: https://metallb.github.io/metallb