apiVersion: v1
kind: Secret
metadata:
  name: metallb-helm-repo
  namespace: argocd # This HAS to be your Argo CD namespace
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: metallb
  type: helm
  url: https://metallb.github.io/metallb
