apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-k8s-n37-ca-staging
spec:
  acme:
    email: imcbeth1980@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-k8s-n37-ca-key-staging
    solvers:
      - dns01:
          cloudflare:
            email: imcbeth1980@gmail.com 
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-k8s-n37-ca-prod
spec:
  acme:
    email: imcbeth1980@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-k8s-n37-ca-key-prod
    solvers:
      - dns01:
          cloudflare:
            email: imcbeth1980@gmail.com 
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
