apiVersion: v1
kind: Secret
metadata:
  name: mojo2600-helm-repo
  namespace: argocd # This HAS to be your Argo CD namespace
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: mojo2600
  type: helm
  url: https://mojo2600.github.io/pihole-kubernetes/
