# localstack-manifests/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  replicas: 1
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest # Or a specific version
          ports:
            - containerPort: 4566 # Default LocalStack port
          env:
            - name: SERVICES
              value: s3,sqs,lambda # Example services
            - name: DEBUG
              value: "1"
